language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t devops/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devops/docker-react npm run test -- --coverage